name: CI Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: tree
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
      - run: npm run check-types
      - run: npm run coverage
